services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Works for host access; for container-to-container we'll use kafka:9092 from Spark job
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16
    container_name: oilgas-postgres
    environment:
      POSTGRES_DB: oilgas
      POSTGRES_USER: oilgas
      POSTGRES_PASSWORD: oilgas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: apache/spark:3.5.1
    container_name: spark
    working_dir: /opt/project
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - 0.0.0.0
      - --port
      - "7077"
      - --webui-port
      - "8080"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./:/opt/project

volumes:
  postgres_data:
